config/routes.rb
Rails.application.routes.draw do

  root 'records_users#index'

  devise_for :users

  resources :records_users do
  	get 'explore', on: :collection
  end

  resources :records, only: [:create, :update] do
  	get 'artist_overview', on: :collection
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/records_user.rb
class RecordsUser < ApplicationRecord
	belongs_to :user 
	belongs_to :record

	delegate :album_title, to: :record, allow_nil: true
	delegate :artist, to: :record, allow_nil: true
	delegate :year, to: :record, allow_nil: true

	# require users to rate albums - better statistical analysis; potentially lower user engagement / total records added 
	validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 1, less_than_or_equal_to: 10 }

	enum condition: { unopened: 1, brand_new: 2, excellent: 3, very_good: 4, good: 5, acceptable: 6, some_damage: 7 }


	def self.most_popular_owned_record
		Record.find(RecordsUser.group("record_id").count.max_by{|record_id, freq| freq}[0])
	end

	def self.recently_trending
		recent_date = Date.today - 1.month
		recently_added_records = RecordsUser.where("created_at >= ?", recent_date)
		if recently_added_records.any?
			Record.find(recently_added_records.group("record_id").count.max_by{|record_id, freq| freq}[0])
		else
			recently_added_records = RecordsUser.where(created_at >= (Date.today - 6.month))
			recently_added_records.empty? ? most_popular_owned_record : Record.find(recently_added_records.group("record_id").count.max_by{|record_id, freq| freq}[0])
		end
	end

	def self.most_favorited
		Record.find(RecordsUser.where(favorite: true).group("record_id").count.max_by{|record_id, total| total})[0]
	end

	def self.highest_rated
		Record.find(RecordsUser.group("record_id").average("rating").max_by{ |record_id, av_rating| av_rating }.first )
	end

	def self.highly_rated_unique
		# "hipster"
		# there's a bias: the fewer ratings, the higher the average rating is likely to be
		rating_greater_or_equal_to = 7
		record_id_high_av_rating = RecordsUser.group("record_id").average("rating").keep_if{|record_id, av_rating| av_rating>= 7.0}.keys
		record_id_freq = RecordsUser.where(record_id: record_id_high_av_rating).group("record_id").count.min_by{|rec_id, freq| freq}
		Record.find(record_id_freq[0])
	end

	def self.recommended_based_on_most_recently_added_record(current_user_id, record_added_id=nil)
		most_recent_purchase_date = RecordsUser.where(user_id: current_user_id).maximum("created_at")
		(@record = most_popular_owned_record) if most_recent_purchase_date.blank?
		record_added_id ||= RecordsUser.where(created_at: most_recent_purchase_date)[0].record_id

		user_ids_who_own_same_record_user_just_added = RecordsUser.where(record_id: record_added_id).pluck(:user_id) - [current_user_id]
		record_frequency_by_users_who_own_same_record = RecordsUser.where(user_id: user_ids_who_own_same_record_user_just_added).group("record_id").count
		(@record = most_popular_owned_record) if record_frequency_by_users_who_own_same_record.blank?
		# delete records user already owns in frequency / rec id table
		record_frequency_by_users_who_own_same_record.delete_if{|record_id, freq| User.find(current_user_id).records.pluck(:id).include?(record_id) }
		(@record = most_popular_owned_record) if record_frequency_by_users_who_own_same_record.blank?
		@record ||= Record.find(record_frequency_by_users_who_own_same_record.max_by{|record_id, frequency| frequency}[0])
	end

	def self.record_analysis_stats(current_user_id, record_added_id=nil)
	    @most_popular_owned_record = RecordsUser.most_popular_owned_record
	    @recently_trending = RecordsUser.recently_trending
	    @most_favorited = RecordsUser.most_favorited
	    @highest_rated = RecordsUser.highest_rated
	    @highly_rated_unique = RecordsUser.highly_rated_unique
	    @recommended_based_on_most_recently_added_record = RecordsUser.recommended_based_on_most_recently_added_record(current_user_id, record_added_id)

		{ most_popular_owned_record: "Album #{@most_popular_owned_record.album_title.capitalize} by #{@most_popular_owned_record.artist.capitalize}",
	    recently_trending: "Album #{@recently_trending.album_title.capitalize} by #{@recently_trending.artist.capitalize}",
	    most_favorited: "Album #{@most_favorited.album_title.capitalize} by #{@most_favorited.artist.capitalize}",
	    highest_rated: "Album #{@highest_rated.album_title.capitalize} by #{@highest_rated.artist.capitalize}",
	    highly_rated_unique: "Album #{@highly_rated_unique.album_title.capitalize} by #{@highly_rated_unique.artist.capitalize}",
	    recommended_based_on_most_recently_added_record: "Album #{@recommended_based_on_most_recently_added_record.album_title.capitalize} by #{@recommended_based_on_most_recently_added_record.artist.capitalize}"}
	end

end

app/controllers/records_users_controller.rb
class RecordsUsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_records_user, only: [:show, :edit, :update, :destroy]
  before_action :check_if_user_permitted_to_change_records_user, only: [:show, :edit, :update, :destroy]

  # GET /records_users
  # GET /records_users.json
  def index
    @records_users = RecordsUser.where(user_id: current_user.id)#current_user.records
    
  end

  def explore
    @analysis_stats_and_recommendations = RecordsUser.record_analysis_stats(current_user.id)
  end

  # GET /records_users/1
  # GET /records_users/1.json
  def show
    @recommended_based_on_most_recently_added_record = RecordsUser.recommended_based_on_most_recently_added_record(current_user.id, @records_user.id)
  end

  # GET /records_users/new
  def new
    @records_user = RecordsUser.new
  end

  # GET /records_users/1/edit
  def edit
  end

  # POST /records_users
  # POST /records_users.json
  def create
    # keep valid records but with user who never provides condition, etc.
    @records_user = RecordsUser.new(records_user_params)
    @records_user.user_id = current_user.id

    if Record.new(record_params).valid? 
        record = Record.find_by(album_title: record_params[:album_title], artist: record_params[:artist], year: record_params[:year]) || Record.create(record_params)
      @records_user.record_id = record.id
    end

    respond_to do |format|
      if @records_user.save
        format.html { redirect_to @records_user, notice: 'Record user was successfully created.' }
        format.json { render :show, status: :created, location: @records_user }
      else
        format.html { render :new }
        format.json { render json: @records_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /records_users/1
  # PATCH/PUT /records_users/1.json
  def update
    @records_user.user_id = current_user.id

    if Record.new(record_params).valid? 
      record = Record.find_by(album_title: record_params[:album_title], artist: record_params[:artist], year: record_params[:year]) || Record.create(record_params)
      @records_user.record_id = record.id
    else
      @records_user.record_id = nil
    end

    respond_to do |format|
      if @records_user.update(records_user_params)
        format.html { redirect_to @records_user, notice: 'Record user was successfully updated.' }
        format.json { render :show, status: :ok, location: @records_user }
      else
        format.html { render :edit }
        format.json { render json: @records_user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /records_users/1
  # DELETE /records_users/1.json
  def destroy
    @records_user.destroy
    respond_to do |format|
      format.html { redirect_to records_users_url, notice: 'Record user was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_records_user
      @records_user = RecordsUser.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def records_user_params
      params[:records_user][:condition] = params[:records_user][:condition].downcase.gsub(' ', '_') if params[:records_user][:condition]

      params.require(:records_user).permit(:condition, :rating, :favorite)
    end
    
    def record_params 
      params.require(:records_user).permit(:album_title, :year, :artist)
    end

    def check_if_user_permitted_to_change_records_user
      unless (@records_user.user_id == current_user.id)
        handle_unauthorized_users
      end
    end

    def handle_unauthorized_users
      respond_to do |format|
        format.html { redirect_to records_users_path, notice: 'You are not authorized to perform this action.' }
        format.json { render json: {}, status: :unauthorized }
      end   
    end

end

app/views/records_users/_form.html.erb
<%= form_for(@records_user) do |f| %>
  <% if @records_user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@records_user.errors.count, "error") %> prohibited this records_user from being saved:</h2>

      <ul>
      <% @records_user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


  <div class="field">
    <%= f.label :album_title %>
    <%= f.text_field :album_title %>
  </div>

  <div class="field">
    <%= f.label :artist %>
    <%= f.text_field :artist %>
  </div>

  <div class="field">
    <%= f.label :year %>
    <%= f.number_field :year %>
  </div>


  <div class="field">
    <%= f.label :condition %>
    <%= f.select(:condition, ["Unopened", "Brand New", "Excellent", "Very Good", "Good", "Acceptable", "Some Damage"]) %>
  </div>

  <div class="field">
    <%= f.label "Rate on a scale from 1-10, 10 being the best:" %>
    <%= f.number_field :rating %>
  </div>

  <div class="field">
    <%= f.label :favorite %>
    <%= f.check_box :favorite %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/records_users/edit.html.erb
<h1>Editing Record User</h1>

<%= render 'form', records_user: @records_user %>

<%= link_to 'Show', @records_user %> |
<%= link_to 'Back', records_users_path %>

app/views/records_users/explore.html.erb
<h3>Looking for inspiration? Recommendations? Want to know how unique your collection is?</h3>
<% @analysis_stats_and_recommendations.each do |title, record| %>
		<strong><%= title.to_s.gsub('_', ' ').capitalize %>:</strong>
		<%= record %>
	</br>
<% end %>

app/views/records_users/index.html.erb
<h1>Your Record Collection:</h1>

<table>
  <thead>
    <tr>
      <th>Album title</th>
      <th>Artist</th>
      <th>Year</th>
      <th>Condition</th>
      <th>Rating</th>
      <th>Favorite</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @records_users.each do |records_user| %>
      <tr>
        <td><%= records_user.album_title %></td>
        <td><%= records_user.artist %></td>
        <td><%= records_user.year %></td>
        <td><%= records_user.condition.gsub('_', ' ').split.map(&:capitalize).join(" ") %></td>
        <td><%= records_user.rating %></td>
        <td><% if records_user.favorite %>&#9734;<% end %></td>
        <td><%= link_to 'Show', records_user %></td>
        <td><%= link_to 'Edit', edit_records_user_path(records_user) %></td>
        <td><%= link_to 'Destroy', records_user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/records_users/new.html.erb
<h1>New Records User</h1>

<%= render 'form', records_user: @records_user %>

<%= link_to 'Back', records_users_path %>

app/views/records_users/show.html.erb
<p>
  <strong>Album Title:</strong>
  <%= @records_user.album_title %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @records_user.artist %>
</p>

<p>
  <strong>Year:</strong>
  <%= @records_user.year %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @records_user.rating %>
</p>

<p>
  <strong>Condition:</strong>
  <%= @records_user.condition.gsub('_', ' ').split.map(&:capitalize).join(" ") %>
</p>

<p>
  <strong> <% if @records_user.favorite %>Favorited &#9734;<% end %></strong>
</p>

<p>
  <strong>Other users who added this record to their collection have liked: the album
  <%= @recommended_based_on_most_recently_added_record.album_title.to_s.gsub('_', ' ').capitalize  %> by
  <%= @recommended_based_on_most_recently_added_record.artist.capitalize %>, released in
  <%= @recommended_based_on_most_recently_added_record.year %>.
  </strong>
</p>

<%= link_to 'Edit', edit_records_user_path(@records_user) %> |
<%= link_to 'Back', records_users_path %>